### ISSUE TITLE
Nurbs Error

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas_viewer#116]
Not sure if it is a viewer problem, but Nurbs example often raise this error. If it goes away if I run the example again.

(compas-dev) D:\Github\compas_viewer>C:/Users/leoch/anaconda3/envs/compas-dev/python.exe d:/Github/compas_viewer/docs/examples/object/nurbs.py
Traceback (most recent call last):
  File "d:\Github\compas_viewer\docs\examples\object\nurbs.py", line 20, in <module>
    viewer.show()
  File "D:\Github\compas_viewer\src\compas_viewer\viewer.py", line 184, in show
    self.window.show()
  File "D:\Github\compas_viewer\src\compas_viewer\components\renderer\renderer.py", line 173, in initializeGL
    self.init()
  File "D:\Github\compas_viewer\src\compas_viewer\components\renderer\renderer.py", line 377, in init
    obj.init()
  File "D:\Github\compas_viewer\src\compas_viewer\scene\sceneobject.py", line 294, in init
    self._frontfaces_data = self._read_frontfaces_data()
  File "D:\Github\compas_viewer\src\compas_viewer\scene\geometryobject.py", line 111, in _read_frontfaces_data
    if self.viewmesh is None:
  File "D:\Github\compas_viewer\src\compas_viewer\scene\nurbssurfaceobject.py", line 47, in viewmesh
    return self.geometry.to_tesselation()
  File "d:\github\compas_occ\src\compas_occ\geometry\surfaces\surface.py", line 186, in to_tesselation
    tess.Compute()
  File "C:\Users\leoch\anaconda3\envs\compas-dev\lib\site-packages\OCC\Core\Tesselator.py", line 250, in Compute
    return _Tesselator.ShapeTesselator_Compute(self, compute_edges, mesh_quality, parallel)
RuntimeError: Standard_OutOfRangeNCollection_AliasedArray::value(), out of range index raised from method Compute of class ShapeTesselator

**Comment by tomvanmele** [comment]
@Licini is this now solved by using the brep tessellator? can we close?
