### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by petrasvestartas** [compas-dev/compas_viewer#200]
Tag object does not work on Ubuntu:

https://github.com/compas-dev/compas_viewer/blob/main/scripts/tag.py

```
Traceback (most recent call last):
  File "/home/petras/brg/2_code/compas_grid/src/compas_grid/grid_model.py", line 11, in <module>
    viewer.show()
  File "/home/petras/anaconda3/envs/grid/lib/python3.9/site-packages/compas_viewer/viewer.py", line 83, in show
    self.ui.init()
  File "/home/petras/anaconda3/envs/grid/lib/python3.9/site-packages/compas_viewer/ui/ui.py", line 54, in init
    self.window.widget.show()
  File "/home/petras/anaconda3/envs/grid/lib/python3.9/site-packages/compas_viewer/renderer/renderer.py", line 258, in event
    return super().event(event)
  File "/home/petras/anaconda3/envs/grid/lib/python3.9/site-packages/compas_viewer/renderer/renderer.py", line 187, in initializeGL
    self.init()
  File "/home/petras/anaconda3/envs/grid/lib/python3.9/site-packages/compas_viewer/renderer/renderer.py", line 396, in init
    obj.init()
  File "/home/petras/anaconda3/envs/grid/lib/python3.9/site-packages/compas_viewer/scene/sceneobject.py", line 266, in init
    self.make_buffers()
  File "/home/petras/anaconda3/envs/grid/lib/python3.9/site-packages/compas_viewer/scene/tagobject.py", line 138, in make_buffers
    "text_texture": self.make_text_texture(),
  File "/home/petras/anaconda3/envs/grid/lib/python3.9/site-packages/compas_viewer/scene/tagobject.py", line 143, in make_text_texture
    face = Face(self.geometry.font)
  File "/home/petras/anaconda3/envs/grid/lib/python3.9/site-packages/freetype/__init__.py", line 1192, in __init__
    raise FT_Exception(error)
freetype.ft_errors.FT_Exception: FT_Exception:  (cannot open resource)
```

**Comment by ChiaChing-Yen** [comment]
May this issue be closed?  I have tested the same example with the latest version, and it is now functioning correctly.
